/*
 * Copyright 2023 - 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.eastrobot.arch.llms.model;

import java.util.List;

/**
 * 表示从AI模型接收到的响应的接口.
 * 该接口提供了访问AI模型生成的主要结果或结果列表的方法，以及响应元数据。
 * 它作为一种标准化的方式来封装和管理AI模型的输出，确保生成的信息易于检索和处理。
 *
 * @param <T> 人工智能模型提供的结果类型
 * @author han.sun
 * @since 6.0.0
 */
public interface ModelResponse<T extends ModelResult<?>> {

    /**
     * Retrieves the result of the AI model.
     *
     * @return the result generated by the AI model
     */
    T getResult();

    /**
     * Retrieves the list of generated outputs by the AI model.
     *
     * @return the list of generated outputs
     */
    List<T> getResults();

    /**
     * Retrieves the response metadata associated with the AI model's response.
     *
     * @return the response metadata
     */
    ResponseMetadata getMetadata();

}
